#!/usr/bin/env python3
# ****************************************************************************
# CUI
#
# The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
#
# Copyright 2020 Infoscitex, a DCS Company. All rights reserved.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ****************************************************************************

# This script resolves issues in sphinx-build generated .tex files of AFSIM source documentation
# Most issues derive from custom rst directives and custom blocking grammar defined
# in afsim/cmake/Modules/sphinx/extensions/wsf-python<#>.py
# It's possible that expanding the custom grammar in those definitions may render texfix
# unnecessary. If changes are made in that context, components using texfix will remain functional.

import io
import os
import sys
import array
import re

# LatexCrossReferenceConverter
# Designed to parse .tex files generated by sphinx-build,
# identify cross-references which are undefined in latexmk (latex_engine pdflatex)
# and resolve undefined references prior to latexmk processing.
class LatexCrossReferenceConverter:

   # Object Initialization
   def __init__(self, aTgtSearchRegEx, aRefSearchRegEx, aConversionLineKeyword, aTgtSigPartDelim = ":", aRefSigPartDelim = ":", aTgtSigListDelim = ","):
      self.mTgtSearchRegEx = aTgtSearchRegEx                     # The Regular Expression to identify targets in a given file.
      self.mRefSearchRegEx = aRefSearchRegEx                     # The Regular Expression to identify cross-references in a given files.
      self.mConversionLineKeyword = aConversionLineKeyword       # A qualifying keyword that must occur on a given line to allow potential conversion
      self.mTgtSignaturePartDelimiter = aTgtSigPartDelim         # A delimiting character that occurs in a given target signature set (Normally ":")
      self.mRefSignaturePartDelimiter = aRefSigPartDelim         # A delimiting character that occurs in a given reference signature set (Normally ":", but not for indicies)
      self.mTgtSignatureListStringDelimiter = aTgtSigListDelim   # Format a list string with an appropriate delimiter (ideally one that doesn't occur in list entries) (default ",")
      self.mTgtSignatureList = []                                # List to store all latex hyperlink target signatures
      self.mTgtSignatureListString = ""                          # String to store contents of the previous list (for faster RegEx processing)
      self.mRefSignatureList = []                                # List to store all latex cross-reference signatures
      self.mUndefinedRefSignatureList = []                       # List to store all latex cross-references that are not defined in the hyperlink target signatures list
      self.mConversionMap = [[],[]]                              # Map to define conversions of malformed references to defined targets

   # Convenience method to fill mTgtSignatureList and save the list as a string
   def CreateTgtList(self, aFileObj):
      self.mTgtSignatureList = self.FileFindEach(aFileObj, self.mTgtSearchRegEx)
      self.mTgtSignatureListString = self.ListToString(self.mTgtSignatureList)

   # Convenience method to fill mRefSignatureList
   def CreateRefList(self, aFileObj):
      self.mRefSignatureList = self.FileFindEach(aFileObj, self.mRefSearchRegEx)

   # Identify the cross-reference signatures that don't map to a target signature (must be exact match to be "defined")
   def FindUndefinedRefs(self):
      for ref in self.mRefSignatureList:
         tgtStyleRef = ref
         if self.mRefSignaturePartDelimiter != self.mTgtSignaturePartDelimiter: # Conversion condition for index items
            tgtStyleRef = ref.replace(self.mRefSignaturePartDelimiter, self.mTgtSignaturePartDelimiter)
         if tgtStyleRef not in self.mTgtSignatureList:
            self.mUndefinedRefSignatureList.append(ref)

   # Attempt to map malformed cross-reference signatures to the appropriate target signature
   def MapUndefinedRefs(self):
      # First, try to maps refs to tgts by filling in missing blocking information
      # (i.e. Input signature "docs/platform:icon" maps to target signature "docs/platform:platform.icon")
      # This is imperfect because identically named commands infrequently exist in the same file within different blocks.
      # However, testing revealed that in HTML, cases like this map every command to the target in the first block.
      # While that behavior is also incorrect, an may need to be addressed separately, this maintains behavioral consistency.
      tempList = []
      for undefinedRefSig in self.mUndefinedRefSignatureList:
         sigParts = undefinedRefSig.split(self.mRefSignaturePartDelimiter)
         searchSuffix = self.AddExpandedRegExSearchCoverage(sigParts[1])
         searchSig = sigParts[0] + r'(:.*\.|:)' + searchSuffix + self.mTgtSignatureListStringDelimiter
         if not self.MapUndefinedCrossRef(undefinedRefSig, searchSig):
            tempList.append(undefinedRefSig)
      self.mUndefinedRefSignatureList = tempList

      # If mapping is unsuccessful, usually due to implicitly defined targets, or unconventional labeling,
      # Map all remaining refs to the beginning of the file they reference.
      # (i.e. Input signature "docs/classexample:SimpleClass" maps to target signature "docs/classexample:example-of-a-class")
      # This is imperfect, but rarely necessary and it maintains abstraction from edge cases
      for undefinedRefSig in self.mUndefinedRefSignatureList:
         sigParts = undefinedRefSig.split(self.mRefSignaturePartDelimiter)
         searchSig = sigParts[0] + r':.*' + self.mTgtSignatureListStringDelimiter
         self.MapUndefinedCrossRef(undefinedRefSig, searchSig)

   # Look for a signature match based on aSearchSig and if found,
   # record the map entry in mConversion map.
   def MapUndefinedCrossRef(self, aOldRefSig, aSearchSig):
      match = re.search(aSearchSig, self.mTgtSignatureListString, re.IGNORECASE)
      if match:
         newRefSig = match.group()[:-1]
         if self.mRefSignaturePartDelimiter != self.mTgtSignaturePartDelimiter:
            newRefSig = newRefSig.replace(self.mTgtSignaturePartDelimiter, self.mRefSignaturePartDelimiter)
         if newRefSig != aOldRefSig:
            self.mConversionMap[0].append("{" + aOldRefSig + "}") # Parenthesis "{" and "}" delimiters safeguard against erroneous substring changes during conversion.
            self.mConversionMap[1].append("{" + newRefSig + "}")  # (i.e. Prevents cmd:cmd -> cmd:cmd.cmd from changing cmd:cmd_suffix to cmd:cmd.cmd_suffix)
         return True
      else:
         return False

   # Convenience method to produce a string from a list.
   # RegEx matching is significantly faster this way.
   def ListToString(self, aList):
      listString = ""
      for entry in aList:
         listString += entry + self.mTgtSignatureListStringDelimiter + "\n"
      return listString

   # Identifies and records pattern occurrences in aFileObj qualified by aRegEx.
   def FileFindEach(self, aFileObj, aRegEx):
      aFileObj.seek(0)
      matchList = [re.findall(aRegEx, aFileObj.read())]
      return self.RemoveDuplicateEntries(matchList)

   # Remove duplicate pattern entries immediately re.findall() for faster post-processing.
   # Also, reformat to one-dimensional list for simplified post-processing.
   # Note: This prunes any reference instance that occurs more than once, as only a single
   #       entry is needed for the conversion map.
   # Note: This also removes multiply defined references from the target list, which are
   #       identified as warnings by latexmk, but not addressed by texfix (yet).
   @staticmethod
   def RemoveDuplicateEntries(aRegExFindAllList, aTruncateExpression ="("):
      seen = []
      filteredList = []
      for entrySet in aRegExFindAllList:
         for entry in entrySet:
            if entry not in seen:
               seen.append(entry)
               truncatedEntry = entry.split(aTruncateExpression)[0]
               filteredList.append(truncatedEntry)
      return filteredList

   # This helper function allows the signature to be redefined to match specific characters with others.
   # By default it allows underscore "_" to match with "-" before attempting to map a reference to a target.
   # Additionally it removes template and macro prefixes and suffixes which are inherently removed from base
   # target signatures by sphinx-build.
   @staticmethod
   def AddExpandedRegExSearchCoverage(aSigSuffix, aWordDelimiter = "_", aExpandedWordDelimiter = r'([_\-])'):
      newSigSuffix = aSigSuffix
      if aSigSuffix.endswith(">"):
         newSigSuffix = aSigSuffix.split("<")[0]
      elif aSigSuffix.endswith("__"):
         newSigSuffix = aSigSuffix.split("__")[0]
      if aWordDelimiter in newSigSuffix:
         newSigSuffix = newSigSuffix.replace(aWordDelimiter, aExpandedWordDelimiter)
      return newSigSuffix

# This function makes changes to the target file based on the converters passed in.
def ApplyReferenceConversions(aFileObj, aConverterSet):
   print(" Resolving references in", aFileObj.name, "...")
   inFile  = aFileObj.name
   outFile = inFile[:-4] + '.tmp'            # Save the target document text, with changes, line by line to a temp file of the same name.
   fo = open(outFile, 'w', encoding="utf-8")
   linesChanged = 0
   pysiglineFixInProgress = False
   aFileObj.seek(0)
   for line in aFileObj:
      newLine = line
      for cvtr in aConverterSet:
         if cvtr.mConversionLineKeyword in newLine:                       # Prevent a target signatures from being changed,
            preRefSection = line[:line.find(cvtr.mConversionLineKeyword)] # while still allowing reference changes if/when
            oldRefSection = line[line.find(cvtr.mConversionLineKeyword):] # a reference occurs on the same line as a target.
            newRefSection = oldRefSection
            for i in range(len(cvtr.mConversionMap[0])):
               tmpRefSection = newRefSection
               newRefSection = tmpRefSection.replace(cvtr.mConversionMap[0][i], cvtr.mConversionMap[1][i])
            newLine = preRefSection + newRefSection
      newLine, pysiglineFixInProgress = PysiglineFix(newLine, pysiglineFixInProgress)
      if newLine != line:
         linesChanged += 1
      fo.write(newLine)
   print(" References resolved with", linesChanged, "Lines Changed. \n")

   fo.close()                 # Release the temp file.
   aFileObj.close()           # Release the input file.
   os.remove(inFile)          # Delete the input file.
   os.rename(outFile, inFile) # Rename the temp file to the name of the input file.

   aFileObj = open(inFile, 'r', encoding="utf-8") # Reopen the modified tex file,
   return aFileObj                                # and return it so that this function can be called again if necessary.

# Helper function to handle class definition lines which don't appear in the pdf if they include directive flags
# This is also an issue with custom directives in afsim/cmake/Modules/sphinx/extensions/wsf-python<#>.py
# (i.e. .. class:: WsfPlatform inherits WsfObject
#          :arrow:)
def PysiglineFix(aLine, aFixInProgress):
   if aLine.startswith("\\pysigline{") and aLine.count("{") != aLine.count("}"):
      newLine = aLine[:-1] + "}\n"
      return newLine, True
   elif aLine.startswith("}") and aFixInProgress:
      newLine = ""
      return newLine, False
   else:
      return aLine, aFixInProgress



# Helper function to keep directory navigation clean
# because texfix is not in the project root.
def AscendDirTree(aPath, aNum):
   workingDir = aPath
   for i in range(aNum):
      workingDir = os.path.dirname(workingDir)
   return workingDir

# Main
def main():
   texFilePath = sys.argv[1]

   texFile = open(texFilePath, "r", encoding="utf-8")
   print("\n Parsing", texFilePath, "for unresolved references... ")

   # Regular Expressions for searching the .tex file.
   tgtSearchRegEx = r'\\label{\\detokenize{(.*?)}'
   refSearchRegEx = r'{\\hyperref\[\\detokenize{(.*?)}]'
   idxSearchRegEx = r'\\sphinxstyleindexpageref{(docs/.*\\detokenize{.*?)}'

   LatexRefFixer = LatexCrossReferenceConverter(tgtSearchRegEx, refSearchRegEx, "hyperref")

   LatexRefFixer.CreateTgtList(texFile)
   LatexRefFixer.CreateRefList(texFile)
   LatexRefFixer.FindUndefinedRefs()
   LatexRefFixer.MapUndefinedRefs()

   LatexIdxFixer = LatexCrossReferenceConverter(tgtSearchRegEx, idxSearchRegEx, "sphinxstyleindexpageref", aRefSigPartDelim=":\\detokenize{")

   LatexIdxFixer.CreateTgtList(texFile)
   LatexIdxFixer.CreateRefList(texFile)
   LatexIdxFixer.FindUndefinedRefs()
   LatexIdxFixer.MapUndefinedRefs()

   ApplyReferenceConversions(texFile, [LatexRefFixer, LatexIdxFixer])

   texFile.close()

main()
