// ****************************************************************************
// CUI//REL TO USA ONLY
//
// The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
//
// Copyright 2017-2018 Infoscitex, a DCS Company. All rights reserved.
//
// The use, dissemination or disclosure of data in this file is subject to
// limitation or restriction. See accompanying README and LICENSE for details.
// ****************************************************************************

#include "VersionInfo.hpp"

void Designer::VersionInfo::OutputVersionStringInOutputStream(QTextStream& aOutStream)
{
   aOutStream << "# This file was auto-generated by AFSIM Mover Creator " + QString::fromStdString(GetVersionNumberString()) + "\n";
}
