// ****************************************************************************
// CUI//REL TO USA ONLY
//
// The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
//
// Copyright 2017-2018 Infoscitex, a DCS Company. All rights reserved.
//
// The use, dissemination or disclosure of data in this file is subject to
// limitation or restriction. See accompanying README and LICENSE for details.
// ****************************************************************************

#ifndef VERSION_INFO_HPP
#define VERSION_INFO_HPP

#include "mover_creator_version_defines.hpp"
#include <QTextStream>

// This provides version number support

namespace Designer
{
   namespace VersionInfo
   {
      // This returns the version number as a c-string
      constexpr const char* GetVersionNumberString() { return MOVER_CREATOR_VERSION; }
         
      // This outputs the line:
      //   # This file was auto-generated by the AFSIM Mover Creator <version>
      //   where <version> is replaced by the current version string
      // It i commonly used in output files generated by Mover Creator.
      void OutputVersionStringInOutputStream(QTextStream& aOutStream);
   }
}
#endif // !VERSION_INFO_HPP
