# ****************************************************************************
# CUI
#
# The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ****************************************************************************

[theme]
inherit = basic
stylesheet = wsftheme.css
pygments_style = sphinx

[options]
nosidebar = false
sidebarwidth = 230
rightsidebar = false
stickysidebar = true
collapsiblesidebar = false
externalrefs = true

body_min_width = 0
body_max_width = none
navigation_with_keys = False

footerbgcolor    = #303030
footertextcolor  = #f0f0f0
sidebarbgcolor   = #5B6770
sidebarbtncolor  = #A3AAAE
sidebartextcolor = #f0f0f0
sidebarlinkcolor = #92C0EA
relbarbgcolor    = #16375b
relbartextcolor  = #f0f0f0
relbarlinkcolor  = #f0f0f0
bgcolor          = #ffffff
textcolor        = #303030
headbgcolor      = #ffffff
headtextcolor    = #303030
headlinkcolor    = #303030
linkcolor        = #00308F
visitedlinkcolor = #5C0F8C
codebgcolor      = #DAD9D7
codetextcolor    = #303030
notebgcolor      = #AEAEAC

bodyfont = Helvetica, Arial, sans-serif
headfont = Helvetica, Arial, sans-serif
